### PR TITLE
Update TensorFlow and PyTorch versions

### PR DESCRIPTION
**Pull request by ChrisCummins**
* Bump TensorFlow 1.14.0 -> any
* Bump Torch 1.3.0 -> any
* Add missing requirements to installation instructions

### CODE REVIEW

**Comment by Zacharias030** [comment]
I think we should only accept TF 1.x but not 2 w/o testing it.

**Comment by ChrisCummins** [comment]
The issue is, at least on my system, Tensorflow 1.x cannot be installed :(

```
$ system_profiler SPSoftwareDataType | grep "System Version"
      System Version: macOS 10.15.6 (19G73)

$ python -m pip --version
pip 20.1.1 from /usr/local/Homebrew/lib/python3.8/site-packages/pip (python 3.8)

$ python -m pip install tensorflow==
ERROR: Could not find a version that satisfies the requirement tensorflow== (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
```

Cheers,
Chris

**Comment by Zacharias030** [comment]
I see, that is probably a python 3.8 thing.
Am 12. Aug. 2020, 21:44 +0200 schrieb Chris Cummins <notifications@github.com>:

**Comment by ChrisCummins** [comment]
Merging with the knowledge that this breaks the LSTM if TF 2.x is installed. Will continue to track with #76.

**Pull request merged**
